name: PR Hygiene - PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate-pr-title:
    uses: aerospike/shared-workflows/.github/workflows/reusable_pr-hygiene.yml@90708afc10e3ba52dfcb7857732c796eff6d3f37 # v3.8.2
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr-labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      types-requiring-jira: ""
