name: PR Hygiene - PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate-pr-title:
    uses: aerospike/shared-workflows/.github/workflows/reusable_pr-hygiene.yml@a9e883e43e0d4679ff1a250ea1ef577332a81722 # v3.8.0
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr-labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      types-requiring-jira: ""
